### ISSUE TITLE
In China I can‘t use this software

### ISSUE THREAD

**Issue by Inspire9943** [cs2000/DankDroneDownloader#11]
Hello, I'm in China. When I use the software it said 'DankDroneDownloader no ddd server'. Can I fix this problem by myself? Or it is the server problem? I remember that this software can  be used in China in the old version.  Perhaps you don't have enough money to keep the service in China. 
If you do have any difficulties in this area, I'd be happy to help you. In anyway, it is my hope that I can use the software. Without this precious things, I will feel very inconvenient. Thank you!

**Comment by cs2000** [comment]
As per the release notes, the app doesn't work inside china due to the government imposed firewall. I have absolutely no desire to complicate the app to bypass some dictatorship government.
