### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by zdavatz** [cs2000/DankDroneDownloader#12]
I am trying to connect to my DJI Mavic Pro 2 and I get this:

![Connect](https://user-images.githubusercontent.com/4953/82049833-5a83f380-96b7-11ea-825d-df979db98305.png)

Does the RC have to have an IP Address from the DHCP server in the network?

**Comment by cs2000** [comment]
The issue you're seeing is not with DDD, it is from DUMLDore, a separate program not owned by myself.

**Comment by zdavatz** [comment]
Ah, sorry!

**Comment by zdavatz** [comment]
https://github.com/jezzab/DUMLdore/issues/68
