### ISSUE TITLE
How to debug "No one DDD server active." error

### ISSUE THREAD

**Issue by rlsolomon** [cs2000/DankDroneDownloader#13]
I can reach the online app at http://dankdronedownloader.com/DDD2/app/ and http://dankdronedownloader.co.uk/DDD2/app/ but when I run the Windows executable I'm getting the "No one DDD server active." error.  

I've tried opening the firewall to the .exe and even shutting off the firewall entirely.  

Can you tell me what site is being hit or what criteria is checked for this error?

Am I correct in presuming that if the online app is running that the necessary files/data/sites should be accessible with the windows .exe?  (I would feel silly debugging the client-side, if there actually is a server-side issue!)

Thanks in advance!

**Comment by cs2000** [comment]
As per the release notes, the app doesn't work inside china which is where i suspect you are, this is due to the government imposed firewall. I have absolutely no desire to complicate the app to bypass some dictatorship government.

**Comment by rlsolomon** [comment]
Negative - running inside CONUS (Continental United States) and I was able to download with 7266 (but cannot even if I pull and run the older executable).

Not asking for any app changes at all, just "Can you tell me what site is being hit or what criteria is checked for this error?" so *I* can debug on my side.  Seems fairly certain it's a networking issue on my end, but I don't know what site(s) the app is trying to hit to trace them through my firewall and parental controls, etc.

Thanks in advance for any information you can provide.

**Comment by cs2000** [comment]
Interesting. Well the web app and the desktop app both access the same database, one of these is located on "http://polybotes.feralhosting.com/", assuming you get their landing page, then the app should work for you.

The only difference is with the desktop app, the SQL queries are being sent to/from your machine, whereas on the web app, its all being done server side.

For sure to me it looks like a local issue, as you suspect some kind of parental filter/ISP filter.

Im going to close this issue now as its not an app fault, but hope that gives you some guidance on accessing the desktop app.
