### ISSUE TITLE
Downloading 

### ISSUE THREAD

**Issue by joeb55** [cs2000/DankDroneDownloader#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi I’m wondering which firmware I need to download for my phantom 3. How will I know which to choose to unlock no flight zones .thanks

**Comment by cs2000** [comment]
Hi Joeb, The firmware i supply with DDD is all unmodified, original firmware as was originally served on DJI Assistant 2, none of these firmware's are modified for NFZ removal or any other mods.
