### ISSUE TITLE
Please add support for the DJI Pocket 2

### ISSUE THREAD

**Issue by j9d3it** [cs2000/DankDroneDownloader#15]
Hello, I see you have support for DJI Osmo Pocket. I know the focus is on drones, but could you add support for Pocket 2?

**Comment by cs2000** [comment]
Would love to, but i don't have a source for firmware im afraid. As i dont have one of those devices, i cant grab it from the app, nor is it available from my other sources. If i can find a reliable source, for sure i will add it to the platform.
