### ISSUE TITLE
Bad download link

### ISSUE THREAD

**Issue by Barysman** [cs2000/DankDroneDownloader#16]
Hello.
For Mavic Air RC firmware. 
Instead of firmware V01.00.0200 downloads V01.00.0100_Mavic_Air_RC_dji_system file.

**Comment by cs2000** [comment]
Thanks for the heads-up, i have corrected this in the database now, please try to re-download!

**Comment by Barysman** [comment]
Hello.
I trying to download, but I see an error (404 Not found) message: "Unable to download file". 
The file does not exist in the repository, or may have a different name.

**Comment by cs2000** [comment]
Apologies, the link is now correctly fixed, i made a type on the filename on the database!

**Comment by Barysman** [comment]
Thanks, now it works!
