### ISSUE TITLE
Missing/Wrong Firmwarefile for DJI FPV Racer

### ISSUE THREAD

**Issue by arminf82** [cs2000/DankDroneDownloader#22]
Both on the Homepage and the Windows App when you download the Firmware
V.01.01.0000
for the DJI FPV Racer Remote OR Aircraft you get the same file,
the one for the remote.

**Comment by cs2000** [comment]
@arminf82 Thanks for the heads-up! I have corrected the issue in the database so the app will give you the correct firmware. 

I have also generated you a link (valid for 24 hrs) if you wish to directly download the firmware

[http://dankdronedownloader.com/DDD2/downloader/d.php?t=hP9IfVWsJMe4T8Nb2Fzp0qdjCm6akylABtg3vZXSD71uic5HEwKUYQORnoxr](url)
