### ISSUE TITLE
DJI Mini 2 firmware

### ISSUE THREAD

**Issue by moinmoin68** [cs2000/DankDroneDownloader#24]
Hello Chris, 

I am searching for a special firmware. One of my friends told me that you can help me.  

Best Regards 
moinmoin68

**Comment by cs2000** [comment]
If still required, "Special" firmware can now be purchased using DDD Credits from within the app.

**Comment by moinmoin68** [comment]
Hey Chris can i get an invite for the m***** m*** Group ?

**Comment by cs2000** [comment]
No invite needed, its an open forum, just hit up https://dji-rev.com/login and click the Create an Account button just above the sign-in box :)

**Comment by cs2000** [comment]
![Screenshot 2022-12-08 001157](https://user-images.githubusercontent.com/6414386/206324725-93ffce7f-063b-467b-9ae3-5cafc8dba8b4.png)
