### ISSUE TITLE
Mini 2 firmware 01.00.0320

### ISSUE THREAD

**Issue by timc995** [cs2000/DankDroneDownloader#25]
DDD used to have this firmware version, but it doesn't seem to be available at the moment.
This version allows enables writing gimbal calibration info to the drone, removing the persistent calibration/imu error messages.
Can you please make this version available again?

**Comment by cs2000** [comment]
I have just checked the SQL server and indeed my backups of all firmware files on DDD and cannot find 01.00.0320 for the Mini 2 (WM161)

**Comment by timc995** [comment]
Thanks for looking.  Sorry to hear it's been lost.
If anyone reading this happens to have it (or find it), please reach out!
