### ISSUE TITLE
Coudn't find the fw for M100

### ISSUE THREAD

**Issue by redstonee** [cs2000/DankDroneDownloader#29]
Hi, I was about to get the firmware of Matrice 100 which is said to be supported in the README, however I couldn't find it in the model list. I wonder what is going on, thanks
![image](https://github.com/cs2000/DankDroneDownloader/assets/29058312/8ab20964-9424-4ba9-b5f7-621b771a2a9d)

**Comment by cs2000** [comment]
You are indeed correct, im not sure where those files have gone! Leave it with me and il either get them uploaded if i have them or get that information corrected if it turns out i dont have them!

**Comment by cs2000** [comment]
Turns out i didnt have those files, have updated the supported models list

**Comment by redstonee** [comment]
😭😭😭😭😭😭😭😭😭
