### ISSUE TITLE
Mavic 3 Classic 

### ISSUE THREAD

**Issue by Lukashfreedom** [cs2000/DankDroneDownloader#30]
Good day, installed the program, downloaded the firmware. Uploaded by DUMLdorev3.2. But I can't start flashing. Tell me how to do it correctly. I am a newbie. Thanks for the answer.

**Comment by aytacengin** [comment]
You have to use Drone-Hacks.com application for flashing..

**Comment by cs2000** [comment]
DDD is only a firmware download programme, it doesn't have any flashing component & some models we supply cannot even be flashed, in these instances firmware is made available for archival purposes only.

The best flasher out there is indeed Drone-Hacks, DUMLdore was great, but hasnt been updated up probably 4 years.
