### ISSUE TITLE
Mavic 2 -Pro / Zoom Gimbal Issue

### ISSUE THREAD

**Issue by aytacengin** [cs2000/DankDroneDownloader#31]
I downloaded Gimbal calibration firmware from application.

In this application 01.00.0780 is showing on list ARB2 - But its not ARB2. Its ARB1

So, it coudt be work on ARB2 motherboard. We can not flashing.

If device is ARB1 we are using 01.00.0703 . It is working.. But we will update device. After that problem is coming again.

Do you have ARB2 version of Gimbal Calibration Firmware ? 

Thanks

**Comment by cs2000** [comment]
Everything i have is currently listed on DDD, im afraid if it isnt here i dont have it.
