### ISSUE TITLE
1. How do I view the file I had downloaded? And also, 2. Why won't Drone Hacks detect my drone?

### ISSUE THREAD

**Issue by Maybechangethis** [cs2000/DankDroneDownloader#33]
So I have a DJI Mini 2. I want to fix the Gimbal by recalibrating it using update Ver. 20.06.0200
![image](https://github.com/cs2000/DankDroneDownloader/assets/140295600/4e67618d-d156-4ed0-b8fd-91f6f2d04eb4)
so that I could perhaps actually fix my irritating gimbal warning (40011 err code)
![image](https://github.com/cs2000/DankDroneDownloader/assets/140295600/10b3a2b6-c7b5-4e9f-8186-5aab18198856)

I want to get to use the file I had downloaded and access it. I don't know where the file is. I also want Drone-Hacks.com to detect my drone. 
Still looks like this:
![image](https://github.com/cs2000/DankDroneDownloader/assets/140295600/2779a43e-5696-4ad3-8e11-78ce150f8758)
Perhaps someone who is wiser may be able to assist me in my lack of experience issue.
Thanks! 

~End~ 
There is not yet a end

**Comment by Maybechangethis** [comment]
Oh, I did a wee bit o research and now my only problemo is where is the .bin file?

**Comment by Maybechangethis** [comment]
I give up. Spent 8 hours tryna get somewhere;
2 Steps forward.
2 (and a 1/2) Steps Backward.

**Comment by cs2000** [comment]
Just wanted to comment.

When you download a file, DDD downloads it then asks you where you want to save it, so the BIN file is stored wherever you selected.

If you're having issues with Drone-Hacks, please log a support ticket with them as i dont own Drone-Hacks, we just partner up as our products are of use to each other and our customers/users.
