### ISSUE TITLE
Mini 3 Unable to install firmware

### ISSUE THREAD

**Issue by DJOPING** [cs2000/DankDroneDownloader#35]
![image](https://github.com/cs2000/DankDroneDownloader/assets/67260342/f7148e3a-669f-4053-9b80-16ddfaedda79)
The firmware cannot be accessed by the drone.

**Comment by cs2000** [comment]
Sorry but I cannot assist with flashing issues. DDD only provides the firmware, not guides or support on using it.

**Comment by madkoo** [comment]
@DJOPING  where you able to find the solution ?
