### ISSUE TITLE
Getting the 401 error on latest version

### ISSUE THREAD

**Issue by tfarooqi07** [cs2000/DankDroneDownloader#40]
Unable to get server alive status. Error:  Error: (Status code: Unauthorized) {"type":"https://tools.ietf.org/html/rfc7235#section-3.1","title":"Unauthorized","status":401,"traceId":"00-448d8de4a58b7d70bfc7ce210904de0f-25ad8908b8542596-00"}
=========

Stack trace:
No stack trace for this case

Any updates or ideas? I restarted, ran as admin, turned off firewall and AV

**Comment by cs2000** [comment]
If you receive the message "401 unauthorised" when trying to load the app, please ensure your system time is sync'd with an NTP time server. In 100% of the cases where this has been reported to me, the users system time was off, causing the server to reject the request.
