### ISSUE TITLE
Missing DJI RC-N1 firmware for Mini 2 and Air 2S

### ISSUE THREAD

**Issue by The11thPlague** [cs2000/DankDroneDownloader#41]
I cannot find the firmware for the DJI RC-N1 controller for the Mini 2 and Air 2S.
However, I see there are several "Remote" firmware versions for the Air 2 (without the S).
Is there a way to retrieve it?
What happens if I only update the drone firmware and leave a very old controller firmware?
Thank you.

**Comment by The11thPlague** [comment]
@cs2000 Any advice, please?

**Comment by cs2000** [comment]
I have now located this RC-N1 firmware for the Mavic Air 2s and the Mini 3 Pro and am downloading it. Will get it added as a Remote for both of these devices shortly.

Having an old RC firmware and the latest drone firmware is totally fine and will not cause any issues.

**Comment by The11thPlague** [comment]
@cs2000 Any chance you can find the older RC-N1 firmware v04.12.00.56 for the Mavic Air 2s?
What about the Mini 2?
Thank you.

**Comment by cs2000** [comment]
I have been unable to find anything else in terms of older firmware. I have however added it to my system so i should be collecting this device firmware moving forwards.

Nothing either for the mini 2 RC-N1, i have been unable to locate anything with my methods, sorry :(

**Comment by The11thPlague** [comment]
@cs2000 Thank you for what you did. The downloads now work.
Is there a way I can backup the firmware I have on my controller?

**Comment by cs2000** [comment]
No worries, Sadly not, sorry!
