### ISSUE TITLE
Antirollback value of 02.03.1070

### ISSUE THREAD

**Issue by The11thPlague** [cs2000/DankDroneDownloader#42]
I have an AIR 2S. The factory firmware was 02.03.1070, FC-Version 03.04.07.23.
It had an antirollback value of 0.
I noticed that the same firmware version is available on the website, but the antirollback value is 1.
Is that an error?

**Comment by cs2000** [comment]
Thanks for the info, this was indeed a mistake on my part. The firmware you mentioned does have an ARB of 0. I have corrected this in the database which means its now showing as 0 on the app and website.
