### ISSUE TITLE
DDD not opening on Windows 10 64bit v22H2, 

### ISSUE THREAD

**Issue by Thanu87** [cs2000/DankDroneDownloader#44]
hello sir, can anyone help solve the problem of DDD not opening on Windows 10 64bit v22H2, I have installed the 803 runtime, but it still won't open when I double click the application....

**Comment by cs2000** [comment]
Any errors or anything at all?

**Comment by Thanu87** [comment]
Is the Windows I mentioned not compatible...? Or is there some additional software that I missed...?

**Comment by cs2000** [comment]
No, it is compatible which is why i was asking for any error messages

**Comment by Thanu87** [comment]
No error message appears, but after I click twice there is no response or display on the desktop.

**Comment by Mamay-1551** [comment]
> Якісь помилки чи щось взагалі?

![IMG_20240525_163842](https://github.com/cs2000/DankDroneDownloader/assets/162357745/15b3eed0-5477-4108-a763-2b45ff7ee77f)
Hello sir, can anyone help solve the problem of DDD not opening on Windows 10pro 64bit v22H2!( Can you help solve this problem?

**Comment by cs2000** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/how-to-force-windows-10-time-to-synch-with-a-time/20f3b546-af38-42fb-a2d0-d4df13cc8f43

Sync your PC time with an NTP server.
