### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tlw00988** [cs2000/DankDroneDownloader#47]
Error while updating firmwares. Unable to get server alive status. Error:  Error: (Status code: Unauthorized) {"type":"https://tools.ietf.org/html/rfc9110#section-15.5.2","title":"Unauthorized","status":401,"traceId":"00-8b4e1b888f3a43538affe1b08eabea41-cd82f43822b4c01c-00"}

[ddd_error_log.log](https://github.com/user-attachments/files/15942417/ddd_error_log.log)

**Comment by Knives79** [comment]
me too

**Comment by nu11plex** [comment]
same, waiting for solutions.

**Comment by cs2000** [comment]
This is covered on the main GitHub Readme...

**NOTE: ** If you recieve the message "401 unauthorised" when trying to load the app, please ensure your system time is sync'd with an NTP time server. In 100% of the cases where this has been reported to me, the users system time was off, causing the server to reject the request.

**Comment by tlw00988** [comment]
> This is covered on the main GitHub Readme...
> 
> **NOTE: ** If you recieve the message "401 unauthorised" when trying to load the app, please ensure your system time is sync'd with an NTP time server. In 100% of the cases where this has been reported to me, the users system time was off, causing the server to reject the request.

if my system time not have problen?

**Comment by cs2000** [comment]
System time will be the problem. This error message is literally what that means.

any other issues such as if your IP was blocked or some kind of issue to do with government blocking would give another error.

it literally means you sent a request to the server and the server rejected it, it’s only configured to reject requests if your PC time is off, it’s very strict, only allowing requests -/+ 10 seconds of the actual time reported by Cloudflare.
