### ISSUE TITLE
Unable to get server alive status.

### ISSUE THREAD

**Issue by vinc13008** [cs2000/DankDroneDownloader#48]
Unable to get server alive status. Error:  Error: (Status code: Unauthorized) {"type":"https://tools.ietf.org/html/rfc9110#section-15.5.2","title":"Unauthorized","status":401,"traceId":"00-a546cf6a6f107df38136bf3ff5f2966a-d8e02a0a34c1c739-00"}
=========

**Comment by cs2000** [comment]
This is covered on the main GitHub Readme...

**NOTE: ** If you recieve the message "401 unauthorised" when trying to load the app, please ensure your system time is sync'd with an NTP time server. In 100% of the cases where this has been reported to me, the users system time was off, causing the server to reject the request.
