### ISSUE TITLE
somebody tell me

### ISSUE THREAD

**Issue by mohdzammohd** [cs2000/DankDroneDownloader#50]
![DDD error](https://github.com/user-attachments/assets/3f05150f-4ccb-42e6-b423-059ac76b1001)
can somebody explain to me, why i got this (please refer to pic, TQ )while trying to use DDD.
thanks

**Comment by cs2000** [comment]
This is covered on the main GitHub Readme...

**NOTE: ** If you recieve the message "401 unauthorised" when trying to load the app, please ensure your system time is sync'd with an NTP time server. In 100% of the cases where this has been reported to me, the users system time was off, causing the server to reject the request.

**Comment by mohdzammohd** [comment]
thank you for your assistance.
