### ISSUE TITLE
NOT STARTING

### ISSUE THREAD

**Issue by rtvater** [cs2000/DankDroneDownloader#6]
SERIAL PORT NOT FOUND RECONNECT AND RESTARTB WHAT DO I NEED TO DO

**Comment by cs2000** [comment]
DDD does not use serial ports and this isnt an error message in my software.

**Comment by A77f** [comment]
Good day.  Please tell me where to get the firmware from mavic 2?

**Comment by cs2000** [comment]
![Capture](https://user-images.githubusercontent.com/6414386/62652528-7f428200-b953-11e9-8f0c-5905fcca029f.PNG)
Please do not reply to this thread, this isnt a Q&A section, its for reporting issues.
