### ISSUE TITLE
P3X/P3S lacks changelog

### ISSUE THREAD

**Issue by mefistotelis** [cs2000/DankDroneDownloader#7]
Here's a link to release notes for version v1.10 and all the older versions:
https://dl.djicdn.com/downloads/phantom_3/Phantom+3+Professional+Release+Notes.pdf

Attached are the notes in text form.
[P3X_FW_V01.06.0040-and-before-changelog.txt](https://github.com/cs2000/DankDroneDownloader/files/2716302/P3X_FW_V01.06.0040-and-before-changelog.txt)
[P3X_FW_V01.07.0060-changelog.txt](https://github.com/cs2000/DankDroneDownloader/files/2716303/P3X_FW_V01.07.0060-changelog.txt)
[P3X_FW_V01.08.0080-changelog.txt](https://github.com/cs2000/DankDroneDownloader/files/2716304/P3X_FW_V01.08.0080-changelog.txt)
[P3X_FW_V01.09.0060-changelog.txt](https://github.com/cs2000/DankDroneDownloader/files/2716305/P3X_FW_V01.09.0060-changelog.txt)
[P3X_FW_V01.10.0090-changelog.txt](https://github.com/cs2000/DankDroneDownloader/files/2716306/P3X_FW_V01.10.0090-changelog.txt)

**Comment by mefistotelis** [comment]
And while at it, also changelog for others:
https://dl.djicdn.com/downloads/a3/20180802/A3_release_note_final_EN.pdf
https://dl.djicdn.com/downloads/phantom_3_4k/20170623/Phantom_3_4K_Release_Notes_EN.pdf
https://dl.djicdn.com/downloads/phantom_3/20170706/Phantom+3+Advanced+Release+Notes.pdf

For Ph3 Pro firmware 1.11, I'd use the notes from Ph3 Adv - they should be identical, as the drones only differ in one board within camera.

**Comment by cs2000** [comment]
Perfect thanks, il get them added today
