### ISSUE TITLE
File mislabeled or download did not match selection

### ISSUE THREAD

**Issue by SDubble8** [cs2000/DankDroneDownloader#9]
I saw something about this somewhere in the notes I think, for 2.0. But tried downloading firmware for phantom 4 advanced 1.18 and ended up getting 1.28. Im new to this so am I doing something wrong?

**Comment by cs2000** [comment]
Thanks for the heads up, seems i had a few issues in my database. I think it came when i did some manipulation on the data which i then ran as a script on the entire database, it seems i skipped a line or two which then put the records of file URLs out of step with the Model and Version info. I found the affected 127 lines and this is now fixed !
